name: true
title: false
logo: /Mani/Mani-head.png
description: I am a tropical ecologist but a big fan of data science. I believe that data-driven decision​ making can help businesses and organizations to be more efficient and have strong control over their future directions
theme: jekyll-theme-minimal

##jekyll-theme-minimal 
