name: true
title: false
logo: /Mani/Mani-head.png
description: I am a tropical ecologist but passionate about data science. I believe that data-driven decision making can help business and organization to be more efficient and strong control over the future directions
show_downloads: false
theme: jekyll-theme-minimal

##jekyll-theme-minimal 
