name: true
title: false
logo: /Mani/Mani-head.png
description: Ecologist and a big fan of data science

<br>
  <a href="https://www.linkedin.com/in/manichanhsatdichanh2019/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
##jekyll-theme-minimal 
