name: true
title: false
logo: /Mani/Mani-head.png
description: Hi I am a tropical ecologist but passionate with data science, I believe that data-driven and evidence based organizations will do better with their decision making
show_downloads: false
theme: jekyll-theme-minimal

##jekyll-theme-minimal 
