name: true
title: false
logo: /Mani/Mani-head.png
description: Ecologist and Data Scientist

  <br><br>
  <a href="https://www.linkedin.com/in/manichanhsatdichanh2019/">LinkedIn Profile</a> 

email: "satdicha@hawaii.edu"

theme: jekyll-theme-minimal
##jekyll-theme-minimal 
