name: true
title: false
logo: /Mani/Mani-2.jpeg
description: Data scientist with strong research background and interested in the intersection between big data, sustainability and environment

  <br><br>
  <a href="https://www.linkedin.com/in/manichanhsatdichanh2019/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
##jekyll-theme-minimal 
