title: Manichanh Satdichanh, PhD
subtitle: University of Hawaii
logo: /Mani/Mani-head.jpeg
description: Ecologist but real facinated with data science
show_downloads: true
theme: jekyll-theme-minimal

##jekyll-theme-minimal 
