name: true
title: false
logo: /Mani/Mani-head.png
description: Ecologist and Data Scientist
<br>
I am an ecologist and data scientist studying plant functional ecology and anthropogenic disturbance under climate change. I have more than 15 years of experience working with various types of data, organizations and consulting firms with strong research professional, data analysis, project management, leadership, and critical thinking skills. I believe that data-driven decision​ making can help organizations and businesses to be more efficient and have better predictions for their future directions!
  <br><br>
  <a href="https://www.linkedin.com/in/manichanhsatdichanh2019/">LinkedIn Profile</a> 

url: mailto:satdicha@hawaii.edu
  
theme: jekyll-theme-minimal
##jekyll-theme-minimal 
