name: true
title: false
logo: /Mani/Mani-head.png
description: I am an ecologist but a big fan of data science. I believe that data-driven decision​ making can help organizations and businesses to be more efficient and have better predictions for their future directions
theme: jekyll-theme-minimal
contacts: true
linkedin_username: "https://www.linkedin.com/in/manichanhsatdichanh2019/" #https://www.linkedin.com/in/manichanhsatdichanh2019/
##jekyll-theme-minimal 
